name: Loadson deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install lib folder
      shell: cmd
      run: git clone https://github.com/karlsonmodding/KarlsonFiles.git lib
    - name: Restore NuGet packages
      shell: cmd
      run: dotnet restore
    - name: Run builder
      shell: cmd
      run: Builder.exe
    - name: Upload to deploy branch
      shell: cmd
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add files
        git add loadsonapi
        git add hashmap
        git commit -m "sync with main"
        git push origin deploy
